### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by zeriss** [edgarjrg/queue-for-redux#1]
Some basic documentation would be nice.

**Comment by codingedgar** [comment]
Hi ☀️ ! I'm working on a new version with different design decisions that would properly support with documentation, would be ready by next week, thank you for your interest 👏

**Comment by codingedgar** [comment]
Hi there @zeriss !
The new repository is https://github.com/edgarjrg/redux-action-retry , i'll be taking this one down in a few days.
